// Generated by CoffeeScript 1.7.1
var ReactCoffeeCompiler, coffeescript, transform;

transform = require('coffee-react-transform');

coffeescript = require('coffee-script');

module.exports = ReactCoffeeCompiler = (function() {
  ReactCoffeeCompiler.prototype.brunchPlugin = true;

  ReactCoffeeCompiler.prototype.type = 'javascript';

  ReactCoffeeCompiler.prototype.extension = 'cjsx';

  ReactCoffeeCompiler.prototype.pattern = /\.cjsx/;

  function ReactCoffeeCompiler(config) {
    this.config = config;
  }

  ReactCoffeeCompiler.prototype.compile = function(params, callback) {
    var err, options, source, transformed;
    source = params.data;
    options = {
      bare: true
    };
    try {
      transformed = coffeescript.compile(transform(source), options);
    } catch (_error) {
      err = _error;
      console.log("ERROR: ", err);
      return callback(err.toString());
    }
    return callback(null, {
      data: transformed
    });
  };

  return ReactCoffeeCompiler;

})();
