// Generated by CoffeeScript 1.8.0
var ReactCoffeeCompiler, coffeescript, transform;

transform = require('coffee-react-transform');

coffeescript = require('coffee-script');

module.exports = ReactCoffeeCompiler = (function() {
  ReactCoffeeCompiler.prototype.brunchPlugin = true;

  ReactCoffeeCompiler.prototype.type = 'javascript';

  ReactCoffeeCompiler.prototype.extension = 'cjsx';

  ReactCoffeeCompiler.prototype.pattern = /\.cjsx/;

  function ReactCoffeeCompiler(config) {
    this.config = config != null ? config : {};
    this.sourceMap = !!this.config.sourceMaps || false;
  }

  ReactCoffeeCompiler.prototype.compile = function(params, callback) {
    var data, err, error, loc, options, transformed;
    options = {
      bare: true,
      sourceMap: this.sourceMap,
      sourceFiles: [params.path]
    };
    try {
      transformed = coffeescript.compile(transform(params.data), options);
    } catch (_error) {
      err = _error;
      loc = err.location;
      if (loc) {
        error = loc.first_line + ":" + loc.first_column + " " + (err.toString());
      } else {
        error = err.toString();
      }
      return callback(error);
    }
    if (this.sourceMap) {
      data = {
        data: transformed.js,
        map: transformed.v3SourceMap
      };
    } else {
      data = {
        data: transformed
      };
    }
    return callback(null, data);
  };

  return ReactCoffeeCompiler;

})();
